language: python
cache: pip
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
# command to install dependencies
install:
  - 'pip install -r requirements.txt'
  - 'pip install -e .[test]'
# command to run tests
script: python -m pytest
