sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script: tox
notifications:
  slack:
    secure: Ijls1KCiC2b1SQOGUMFtYIXFs/S+qw3MSq1/TL7EjgsmTWQVHfJMXSyrfZZDo1McETb/M7ViF7Af0gTJip/bcGc5avcYIUHVrJV6W5rM5jXB07dD/uv/9lC4LtjM9TEzHfOS6Ompv6BgvEEqB32lzKFUiBqew53EYWCcwvaWzcbTCZ4nyHiJF2ZothRdIPv8kI9V0ZqUBtKpgqTQMLGVw3HZXE/Iu16X9oY11fRlBMFqAvLMgE6HirKaEori550A67arsT+MWveTYhB8WtEjOG7cXuuGNMkIXrOZKyaRc9bLikMnml6/LkjFEVRye72lTw2RNNAOoA6BxoTWJ3YDXkAITfhqAuFMVFvIdfYYr61PjsAQJg8O7XjYOKzBJU+dxotJXyJ0SZ23s8rpKDb46K6JMdgdhkm4P1SU22eLlhqTNZjenvbA6X+QZL+XC44ER8ghU1IpD8AkYEYVzcjWZUoJQcRdfy4l0tdYl8+1UCvvPBNatoSPkll6krSjtvsBnaKkg1DWkow2BU9NrXpkv/8jqCSfJPTMwZYnJa1MP6fXCtubvAujYiHFAh4cXj/Yrx3cD2OZZcmy1+DkxhKme68eYGf/g5N5QLEpM/Qhgvlt5HzPwFl2o9KffXT4+AR+g8AF5lAXLASsCbTwLGQGsnN0FPzbBJ2lCJrV4Fecwko=
