language: python
cache: pip
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .[test]
script: python -m pytest
notifications:
  slack:
    secure: UjDsrNQUxb+yYMdIcNtz18iZ7YzxJ2JKN/9Ge2PfL51RG/oFSEouSRivUpZrZA8+77gGNy5eWkFa250AG/FahnhMk9yOYkOApGtWyQn5KD4b/DHUo9Pnoz7HZ4c7wQxr5htyl7nVfCH+1aTX+W5oew+WgKNKqsc7QBWVjmQ8y/ZrcZOW60PykNCj1V4mDsc8sMb+6OKagjJ9OsYTDS7/tjpvP+5G9W8zciMLu3rTSBXygiAEhKtaz46E8bwxmnwt5ZbZ3g+c1FYgposkBHWIBRk6CR+x3GR6PMV6DCHOREHduIeWsbBE2H1j97TYl42CL262nRrqTa+D7s/OIIGwpUnncQblZAlXyQ/ljsaDlcGWKY/qCjR1C8e9nILgq0Tlj0nD2Y0YBNaDxMVoHeTxDP4F27UYEKtFMOD2SP9GsNkOoIu1v6WqA8+uuHoaCORcv2UtjpcKeBbDcPNXl2lZJV7dZ2UIyJgsC0VV2nDDxYGQVt0LUniFlR41InP+DZObCxI5pmKc6dLv5kLYLH5tW0VWO1F7EJ7b1G4nJXFrMf+HQeX2XFcPkcml+fO6MZ6SMz9mGGm4yqamaHVM6iaWfTTa9IjhJW8zwx+RcsV+38DzyrcTXFreKxgtb4uI/e3sulE1/KCzCnSljj0b3brKS4ghKXCFgJ+cxohksQvKiAg=
