sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 'pypy'
- 'pypy3'
matrix:
  include:
    - os: 'linux'
    - python: '2.7'
      dist: 'trusty'
    - python: '3.5'
      dist: 'trusty'
    - python: '3.6'
      dist: 'trusty'
    - python: '3.7'
      dist: 'xenial'
      sudo: true
    - python: pypy
      dist: trusty
      sudo: false
    - python: pypy3
      dist: trusty
      sudo: false
install:
- pip install tox-travis
script: tox -- -v
